name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: dark4igi/downsteam/.github/workflows/reusable-workflow.yml@main
    secrets: inherit

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
      - run: echo ${{ needs.job1.outputs.branch }}
