name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  prepare_run:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.get_branch.outputs.branch }}
    steps:
      - id: get_branch
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: prepare_run
    outputs:
      link: ${{ steps.build_downsteam_job_link_env.outputs.link }}
    steps:
      - id: test
        run: echo ${{ needs.prepare_run.outputs.branch }}
        
  job1:
    needs: test
    uses: dark4igi/downsteam/.github/workflows/reusable-workflow.yml@main

                                

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.prepare_run.outputs.branch }} 
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
      - run: echo ${{ needs.job1.outputs.branch }}
