name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  prepare_run:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.get_branch.outputs.branch }}
    steps:
      - id: get_branch
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    needs: prepare_run
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "firstword=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "secondword=world" >> $GITHUB_OUTPUT
        
  test:
    name: test
    runs-on: ubuntu-latest
    needs: example_job
    steps:
      - id: output-first
        run: echo ${{ example_job.outputs.first }}
      - id: output-second
        run: echo ${{ example_job.outputs.second }}
      - id: output-branch
        run: echo ${{ prepare_run.outputs.branch }}
    
